[[images]]
id = "tetris_sheet"
path = "tetris_sheet.png"

[[images]]
id = "bg"
path = "bg.png"
targetPack = "Images"

[[audios]]
id = "rotate_sfx"
path = "rotate_sfx.wav"
type = "Effect"

[[audios]]
id = "lineclear_sfx"
path = "lineclear_sfx.wav"
type = "Effect"

[[audios]]
id = "gameover_sfx"
path = "gameover_sfx.wav"
type = "Effect"

[[audios]]
id = "placeblock_sfx"
path = "placeblock_sfx.wav"
type = "Effect"

[[audios]]
id = "clear_max"
path = "clear_max.wav"
type = "Effect"

[[audios]]
id = "menu_hover"
path = "menu.wav"
type = "Effect"

[[audios]]
id = "title_song"
path = "title_song.wav"
type = "Song"
