[[images]]
id = "bg"
path = "bg.png"

[[images]]
id = "bg2"
path = "bg2.png"

[[images]]
id = "cursor"
path = "cursor.png"

[[images]]
id = "objects"
path = "objects.png"

[[images]]
id = "particles"
path = "particles.png"

[[images]]
id = "bunny"
path = "bunny.png"

[[audios]]
id = "song1"
path = "song1.wav"
type = "Song"

[[audios]]
id = "blip"
path = "menu.wav"
type = "Effect"

[[audios]]
id = "delphi_loop"
path = "delphi_loop.ogg"
type = "Song"

[[audios]]
id = "delphi_loop_wav"
path = "delphi_loop.wav"
type = "Song"