[[shaders]]
id = "canvas2d"
vsPath = "Shaders/canvas2d_vs.sc"
fsPath = "Shaders/canvas2d_fs.sc"

[[images]]
id = "stagelogo"
path = "Textures/stagelogo.png"

[[images]]
id = "stagelogo2"
path = "Textures/stagelogo2.png"

[[fonts]]
id = "monogram"
path = "Fonts/monogram-extended.ttf"
fontSize = "32"

[[fonts]]
id = "impactBits"
path = "Fonts/ImpactBits.ttf"
fontSize = "32"

[[fonts]]
id = "koubit001"
path = "Fonts/koubit_001.ttf"
fontSize = "32"

[[fonts]]
id = "robotY"
path = "Fonts/RobotY.ttf"
fontSize = "32"

[[fonts]]
id = "sportyV2"
path = "Fonts/Born2bSportyV2.ttf"
fontSize = "32"

[[fonts]]
id = "chikareGo2"
path = "Fonts/ChiKareGo2.ttf"
fontSize = "32"
