[[shaders]]
id = "canvas2d"
vsPath = "Shaders/canvas2d_vs.sc"
fsPath = "Shaders/canvas2d_fs.sc"

[[images]]
id = "stagelogo"
path = "Textures/stagelogo.png"

[[images]]
id = "stagelogo2"
path = "Textures/stagelogo2.png"